# -*- coding: utf-8 -*-
"""login.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qwHCi05OTWn7U65pySE12AAPXRUDtp7X
"""

from IPython.display import display, HTML

html_content = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Payroll System</title>
<style>
    body {
        font-family: "Segoe UI", sans-serif;
        /* subtle background gradient */
        background: linear-gradient(135deg, #f2f2f2, #e6e6e6);
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
    }
    .container {
        background-color: white; /* form background */
        padding: 40px;
        border-radius: 12px;
        box-shadow: 0px 4px 20px rgba(0,0,0,0.1);
        width: 350px;
        text-align: center;
    }
    h2 {
        margin-bottom: 20px;
        color: #2d3436;
    }
    input[type="text"], input[type="password"] {
        width: 90%;
        padding: 10px;
        margin: 8px 0;
        border: 1px solid #ccc;
        border-radius: 6px;
        font-size: 14px;
    }
    .captcha-box {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin: 15px 0;
    }
    .captcha {
        background-color: transparent; /* transparent background */
        color: red; /* captcha text in red */
        padding: 10px 20px;
        font-weight: bold;
        font-size: 18px;
        border-radius: 6px;
        letter-spacing: 3px;
    }
    button {
        background-color: #0984e3;
        color: white;
        border: none;
        padding: 10px 20px;
        border-radius: 6px;
        cursor: pointer;
        width: 100%;
        margin-top: 10px;
        font-size: 15px;
    }
    button:hover {
        background-color: #74b9ff;
    }
    .error {
        color: red;
        font-size: 13px;
        margin-top: 10px;
    }
    .toggle-btn {
        margin-top: 10px;
        background: none;
        color: #0984e3;
        text-decoration: underline;
        cursor: pointer;
        font-size: 14px;
    }
</style>
</head>
<body>

<div class="container">
    <h2 id="formTitle">Employee Payroll Login</h2>
    <form id="authForm">
        <input type="text" id="username" placeholder="Username" required><br>
        <input type="password" id="password" placeholder="Password" required><br>

        <div class="captcha-box">
            <div id="captcha" class="captcha"></div>
            <button type="button" onclick="generateCaptcha()">↻</button>
        </div>

        <input type="text" id="captchaInput" placeholder="Enter CAPTCHA" required><br>
        <div id="errorMsg" class="error"></div>

        <button type="submit" id="submitBtn">Login</button>
    </form>
    <button class="toggle-btn" id="toggleForm">Don't have an account? Register</button>
</div>

<script>
let generatedCaptcha = "";
let isLogin = true; // toggle between login and registration

function generateCaptcha() {
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    generatedCaptcha = "";
    for (let i = 0; i < 6; i++) {
        generatedCaptcha += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    document.getElementById("captcha").innerText = generatedCaptcha;
}

// Toggle between login and registration
document.getElementById("toggleForm").addEventListener("click", () => {
    isLogin = !isLogin;
    document.getElementById("formTitle").innerText = isLogin ? "Employee Payroll Login" : "Register New Account";
    document.getElementById("submitBtn").innerText = isLogin ? "Login" : "Register";
    document.getElementById("toggleForm").innerText = isLogin ? "Don't have an account? Register" : "Already have an account? Login";
    document.getElementById("errorMsg").innerText = "";
});

// Handle form submit
document.getElementById("authForm").addEventListener("submit", function(event) {
    event.preventDefault();
    const username = document.getElementById("username").value.trim();
    const password = document.getElementById("password").value.trim();
    const inputCaptcha = document.getElementById("captchaInput").value.trim();
    const errorMsg = document.getElementById("errorMsg");

    if (inputCaptcha !== generatedCaptcha) {
        errorMsg.innerText = "❌ CAPTCHA is incorrect!";
        generateCaptcha();
        return;
    }

    if (!username || !password) {
        errorMsg.innerText = "⚠ Please enter username and password!";
        return;
    }

    if (isLogin) {
        const storedPassword = localStorage.getItem(username);
        if (storedPassword && storedPassword === password) {
            errorMsg.innerText = "";
            alert("✅ Login successful!");
            window.location.href = "https://payrollwebsite-gcbjtfwhyjybtctwh5hpyt.streamlit.app/";
        } else {
            errorMsg.innerText = "❌ Invalid username or password!";
        }
    } else {
        if (localStorage.getItem(username)) {
            errorMsg.innerText = "⚠ Username already exists!";
        } else {
            localStorage.setItem(username, password);
            errorMsg.style.color = "green";
            errorMsg.innerText = "✅ Registration successful! You can login now.";
            setTimeout(() => {
                isLogin = true;
                document.getElementById("formTitle").innerText = "Employee Payroll Login";
                document.getElementById("submitBtn").innerText = "Login";
                document.getElementById("toggleForm").innerText = "Don't have an account? Register";
                errorMsg.innerText = "";
            }, 2000);
        }
    }

    document.getElementById("captchaInput").value = "";
    generateCaptcha();
});

// Generate captcha on page load
window.onload = generateCaptcha;
</script>

</body>
</html>
"""

display(HTML(html_content))